name: test-environment
channels:
  - conda-forge
dependencies:
  - distributed
  - sphinx
  - pyyaml
  - netifaces
  - coveralls
  - coverage
  - codecov
  - behave
  - mock
  - pytest
  - pytest-cov
  - fsspec
  - appdirs
  - setuptools_scm
  - requests
  - requests-mock
  - pip
  - pip:
    - trollsift
    - posttroll
